name = "MimiSNEASY"
uuid = "3f1801d0-c5f8-11e9-1568-bf13fd643260"
version = "1.0.2"

[deps]
Query = "1a8c2f83-1ff3-5112-b086-8aa67b057ba1"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Mimi = "e4e893b0-ee5e-52ea-8111-44b3bdec128c"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
CSVFiles = "5d742f6a-9f54-50ce-8119-2520741973ca"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Query = "1"
julia = "1.6"
Mimi = "1"
DataFrames = "0.19.1, 0.20, 0.21, 0.22, 1.0"
SpecialFunctions = "0.10, 1, 2"
CSVFiles = "0.16, 1"

[targets]
test = ["Test"]
